/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COOKIE_H_RPCGEN
#define _COOKIE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define COOKIE_PROG 0x20000001
#define COOKIE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_cookie 1
extern  int * get_cookie_1(int *, CLIENT *);
extern  int * get_cookie_1_svc(int *, struct svc_req *);
#define remote_exit 2
extern  void * remote_exit_1(int *, CLIENT *);
extern  void * remote_exit_1_svc(int *, struct svc_req *);
extern int cookie_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_cookie 1
extern  int * get_cookie_1();
extern  int * get_cookie_1_svc();
#define remote_exit 2
extern  void * remote_exit_1();
extern  void * remote_exit_1_svc();
extern int cookie_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COOKIE_H_RPCGEN */
