/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cookie.h"

int *get_cookie_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int cookie = 20;
	int tina = 0;
	int client = *argp;
	
	if (cookie >= 0){ //are there enough cookies?
		if (client==1){ //tina
			tina++; //keep track of how many tina has had
			cookie--;
			return 1; // 0=empty,1=yes,2=no
		} else if (client==2){ //judy
			if (tina==2){ //tina's had two so proceed
				tina=0;
				cookie--;
				return 1;
			} else {
				return 2;
			}
		} else {
			perror("bad client ID") // not tina or judy...
		}
	} else {
		return 0; //no more cookies
	}

	return &result;
}

void *remote_exit_1_svc(int *argp, struct svc_req *rqstp)
{
	//static char * result;

	printf("Request for Termination Received\n");
    fflush(NULL);
    exit(0);

	//return (void *) &result;
}
