/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TEST_PROG 0x21140000
#define TEST_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define TEST_PROC 1
extern  int * test_proc_1(int *, CLIENT *);
extern  int * test_proc_1_svc(int *, struct svc_req *);
#define TEST_EXIT 2
extern  void * test_exit_1(int *, CLIENT *);
extern  void * test_exit_1_svc(int *, struct svc_req *);
extern int test_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define TEST_PROC 1
extern  int * test_proc_1();
extern  int * test_proc_1_svc();
#define TEST_EXIT 2
extern  void * test_exit_1();
extern  void * test_exit_1_svc();
extern int test_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
